// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KafkaStudy.Common.Avro
{
    using global::Avro;
    using global::Avro.Specific;

    /// <summary>
    /// Schema de criação de um pedido
    /// </summary>
    public partial class OrderCreatedAvroMessage : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""OrderCreatedAvroMessage"",""namespace"":""KafkaStudy.Common.Avro"",""fields"":[{""name"":""Id"",""doc"":""Id do pedido"",""type"":""string""},{""name"":""CustomerName"",""doc"":""Nome do Cliente"",""type"":""string""},{""name"":""Age"",""doc"":""Idade do Cliente"",""type"":""int""},{""name"":""Qty"",""doc"":""Quantidade de produtos"",""type"":""int""},{""name"":""CartValue"",""doc"":""Valor total do carrinho"",""type"":""double""}]}");
		/// <summary>
		/// Id do pedido
		/// </summary>
		private string _Id;
		/// <summary>
		/// Nome do Cliente
		/// </summary>
		private string _CustomerName;
		/// <summary>
		/// Idade do Cliente
		/// </summary>
		private int _Age;
		/// <summary>
		/// Quantidade de produtos
		/// </summary>
		private int _Qty;
		/// <summary>
		/// Valor total do carrinho
		/// </summary>
		private double _CartValue;
		public virtual Schema Schema
		{
			get
			{
				return OrderCreatedAvroMessage._SCHEMA;
			}
		}
		/// <summary>
		/// Id do pedido
		/// </summary>
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		/// <summary>
		/// Nome do Cliente
		/// </summary>
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				this._CustomerName = value;
			}
		}
		/// <summary>
		/// Idade do Cliente
		/// </summary>
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				this._Age = value;
			}
		}
		/// <summary>
		/// Quantidade de produtos
		/// </summary>
		public int Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				this._Qty = value;
			}
		}
		/// <summary>
		/// Valor total do carrinho
		/// </summary>
		public double CartValue
		{
			get
			{
				return this._CartValue;
			}
			set
			{
				this._CartValue = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.CustomerName;
			case 2: return this.Age;
			case 3: return this.Qty;
			case 4: return this.CartValue;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.CustomerName = (System.String)fieldValue; break;
			case 2: this.Age = (System.Int32)fieldValue; break;
			case 3: this.Qty = (System.Int32)fieldValue; break;
			case 4: this.CartValue = (System.Double)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
